server:
  port: 8083

spring:
  application:
    name: credit-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

controller:
  credit:
    base-path: /credit
    method:
      register-personal: /personal
      register-business: /business
  credit-card:
    base-path: /credit-card
    method:
      register-personal: /personal
      register-business: /business
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  path-variable:
    id: id

customer-service:
  base-url: http://localhost:8099/customers
  method:
    get-personal-customer-by-id: /personal/{id}
    get-business-customer-by-id: /business/{id}
