server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credits
  webflux:
    base-path: /credits

controller:
  credit:
    base-path: /credit
  credit-card:
    base-path: /credit-card
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  path-variable:
    id: id

customer-service:
  base-url: http://localhost:8081/customers
  method:
    get-personal-customer-by-id: /personal/{id}
    get-business-customer-by-id: /business/{id}
